"""
HPV Screening Access and Follow-Up Analytics Platform
Streamlit multipage dashboard.

Run:
    streamlit run app/streamlit_app.py

Prerequisite:
    python src/generate_data.py        # builds data/hpv_screening.db
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.metrics import load_all, build_master, summary_kpis  # noqa: E402
from src.metrics import (  # noqa: E402
    monthly_volume, no_show_by_group, screening_rate_by_education,
    age_distribution, provider_workload, no_show_by_specialty,
    appointments_by_state, facility_type_distribution,
    time_to_follow_up, follow_up_outcomes,
)
from src.modeling import train_and_evaluate, predict_individual, risk_tier  # noqa: E402

DB_PATH = ROOT / "data" / "hpv_screening.db"

# ─── Page config ──────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="HPV Screening Analytics",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Custom CSS ───────────────────────────────────────────────────────────────

st.markdown("""
<style>
    [data-testid="metric-container"] {
        background: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 8px;
        padding: 16px 20px;
    }
    .disclaimer {
        background: #fff3cd;
        border-left: 4px solid #ffc107;
        padding: 10px 14px;
        border-radius: 4px;
        font-size: 0.85rem;
        margin-bottom: 16px;
    }
    h2 { margin-top: 0.5rem; }
</style>
""", unsafe_allow_html=True)

# ─── Data loading (cached) ────────────────────────────────────────────────────

@st.cache_data(show_spinner="Loading data…")
def get_data():
    if not DB_PATH.exists():
        return None, None
    dfs    = load_all(DB_PATH)
    master = build_master(dfs)
    return dfs, master


@st.cache_resource(show_spinner="Training no-show model…")
def get_model(master_hash: int):
    dfs, master = get_data()
    if master is None:
        return None
    return train_and_evaluate(master)


# ─── Sidebar navigation ───────────────────────────────────────────────────────

PAGES = {
    "📊 Overview":             "overview",
    "👥 Demographics":         "demographics",
    "🏥 Providers":            "providers",
    "🗺️ Geography":           "geography",
    "🔮 No-Show Predictor":   "predictor",
}

with st.sidebar:
    st.title("🏥 HPV Screening")
    st.caption("Access & Follow-Up Analytics")
    st.divider()
    page = st.radio("Navigate", list(PAGES.keys()), label_visibility="collapsed")
    st.divider()
    st.caption("Data: synthetic only. Does not represent real patients.")
    st.caption("Built with Streamlit · Plotly · scikit-learn")

PAGE_KEY = PAGES[page]

# ─── Load data ────────────────────────────────────────────────────────────────

dfs, master = get_data()

if dfs is None:
    st.error(
        "Database not found. Run the data generator first:\n\n"
        "```bash\npython src/generate_data.py\n```"
    )
    st.stop()

DISCLAIMER = (
    "⚠️ **Synthetic data only.** All records are generated by the Faker library. "
    "No findings represent real patients, healthcare systems, or populations."
)


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: Overview
# ══════════════════════════════════════════════════════════════════════════════

if PAGE_KEY == "overview":
    st.title("Overview Dashboard")
    st.markdown(f'<div class="disclaimer">{DISCLAIMER}</div>', unsafe_allow_html=True)

    kpis = summary_kpis(dfs)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Patients",       f"{kpis['total_patients']:,}")
    c2.metric("Total Appointments",   f"{kpis['total_appointments']:,}")
    c3.metric("No-Show Rate",         f"{kpis['no_show_rate']:.1%}")
    c4.metric("Abnormal Screening %", f"{kpis['abnormal_rate']:.1%}")

    c5, c6, c7, c8 = st.columns(4)
    c5.metric("Completed Appointments", f"{kpis['completed_appts']:,}")
    c6.metric("Total Screenings",       f"{kpis['total_screenings']:,}")
    c7.metric("Completion Rate",        f"{kpis['screening_rate']:.1%}")
    c8.metric("Follow-Up Completion",   f"{kpis['follow_up_completion']:.1%}",
              help="% of abnormal screenings that received follow-up")

    st.divider()
    col_left, col_right = st.columns(2)

    with col_left:
        st.subheader("Monthly Appointment Volume")
        mv = monthly_volume(master)
        fig = px.line(
            mv, x="year_month",
            y=["appointments", "completed", "no_shows"],
            labels={"value": "Count", "year_month": "Month", "variable": ""},
            color_discrete_map={
                "appointments": "#636EFA",
                "completed":    "#00CC96",
                "no_shows":     "#EF553B",
            },
        )
        fig.update_layout(legend=dict(orientation="h", yanchor="bottom", y=1.02))
        st.plotly_chart(fig, use_container_width=True)

    with col_right:
        st.subheader("Appointment Status Breakdown")
        status_counts = (master
                         .groupby("status")["appointment_id"]
                         .count()
                         .reset_index(name="count"))
        fig2 = px.pie(
            status_counts, values="count", names="status",
            color_discrete_sequence=px.colors.qualitative.Set2,
            hole=0.4,
        )
        fig2.update_traces(textposition="inside", textinfo="percent+label")
        st.plotly_chart(fig2, use_container_width=True)

    col_l2, col_r2 = st.columns(2)

    with col_l2:
        st.subheader("Screening Result Distribution")
        scr_counts = (dfs["screening"]
                      .groupby("result")["screening_id"]
                      .count()
                      .reset_index(name="count")
                      .sort_values("count", ascending=False))
        fig3 = px.bar(
            scr_counts, x="result", y="count",
            color="result",
            color_discrete_sequence=px.colors.qualitative.Pastel,
        )
        fig3.update_layout(showlegend=False)
        st.plotly_chart(fig3, use_container_width=True)

    with col_r2:
        st.subheader("Follow-Up Outcomes")
        fu_out = follow_up_outcomes(dfs)
        fig4 = px.bar(
            fu_out, x="outcome", y="count",
            color="outcome",
            color_discrete_sequence=px.colors.qualitative.Set3,
        )
        fig4.update_layout(showlegend=False, xaxis_tickangle=-20)
        st.plotly_chart(fig4, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: Demographics
# ══════════════════════════════════════════════════════════════════════════════

elif PAGE_KEY == "demographics":
    st.title("Patient Demographics")
    st.markdown(f'<div class="disclaimer">{DISCLAIMER}</div>', unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Age Distribution by Gender")
        age_data = master[master["age"].notna() & master["gender"].isin(["F", "M"])].copy()
        fig = px.histogram(
            age_data, x="age", color="gender",
            nbins=30, barmode="overlay", opacity=0.75,
            labels={"age": "Age (years)", "gender": "Gender"},
            color_discrete_map={"F": "#FF6B9D", "M": "#4ECDC4"},
        )
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Ethnicity Breakdown")
        eth = (master.drop_duplicates("patient_id")
               .groupby("ethnicity")["patient_id"]
               .count()
               .reset_index(name="patients"))
        fig2 = px.pie(
            eth, values="patients", names="ethnicity",
            color_discrete_sequence=px.colors.qualitative.Vivid,
            hole=0.35,
        )
        st.plotly_chart(fig2, use_container_width=True)

    st.divider()
    col3, col4 = st.columns(2)

    with col3:
        st.subheader("No-Show Rate by Insurance Type")
        ns_ins = no_show_by_group(master, "coverage_type")
        fig3 = px.bar(
            ns_ins, x="coverage_type", y="no_show_rate",
            text=ns_ins["no_show_rate"].apply(lambda x: f"{x:.0%}"),
            color="no_show_rate",
            color_continuous_scale="Reds",
            labels={"coverage_type": "Insurance", "no_show_rate": "No-Show Rate"},
        )
        fig3.update_traces(textposition="outside")
        fig3.update_layout(coloraxis_showscale=False, yaxis_tickformat=".0%")
        st.plotly_chart(fig3, use_container_width=True)

    with col4:
        st.subheader("No-Show Rate by Ethnicity")
        ns_eth = no_show_by_group(master, "ethnicity")
        fig4 = px.bar(
            ns_eth, x="ethnicity", y="no_show_rate",
            text=ns_eth["no_show_rate"].apply(lambda x: f"{x:.0%}"),
            color="no_show_rate",
            color_continuous_scale="Oranges",
            labels={"ethnicity": "Ethnicity", "no_show_rate": "No-Show Rate"},
        )
        fig4.update_traces(textposition="outside")
        fig4.update_layout(coloraxis_showscale=False, yaxis_tickformat=".0%",
                           xaxis_tickangle=-20)
        st.plotly_chart(fig4, use_container_width=True)

    st.divider()
    col5, col6 = st.columns(2)

    with col5:
        st.subheader("Screening Completion by Education Level")
        edu = screening_rate_by_education(master)
        fig5 = px.bar(
            edu, x="education_level", y="completion_rate",
            text=edu["completion_rate"].apply(lambda x: f"{x:.0%}"),
            color="completion_rate",
            color_continuous_scale="Greens",
            labels={"education_level": "Education Level", "completion_rate": "Completion Rate"},
        )
        fig5.update_traces(textposition="outside")
        fig5.update_layout(coloraxis_showscale=False, yaxis_tickformat=".0%",
                           xaxis_tickangle=-20)
        st.plotly_chart(fig5, use_container_width=True)

    with col6:
        st.subheader("Screenings Completed by Age Group")
        ag = age_distribution(master)
        fig6 = px.bar(
            ag, x="age_group", y="screenings",
            color="age_group",
            color_discrete_sequence=px.colors.qualitative.Pastel1,
            labels={"age_group": "Age Group", "screenings": "Completed Screenings"},
        )
        fig6.update_layout(showlegend=False)
        st.plotly_chart(fig6, use_container_width=True)

    with st.expander("View raw demographic counts"):
        tab1, tab2 = st.tabs(["By Insurance", "By Ethnicity"])
        with tab1:
            st.dataframe(ns_ins, use_container_width=True)
        with tab2:
            st.dataframe(ns_eth, use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: Providers
# ══════════════════════════════════════════════════════════════════════════════

elif PAGE_KEY == "providers":
    st.title("Provider Performance")
    st.markdown(f'<div class="disclaimer">{DISCLAIMER}</div>', unsafe_allow_html=True)

    pw = provider_workload(master)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Appointment Volume by Provider")
        fig1 = px.bar(
            pw.head(15), x="total_appointments", y="provider_name",
            orientation="h", color="specialty",
            labels={"total_appointments": "Appointments", "provider_name": "Provider"},
        )
        fig1.update_layout(yaxis=dict(autorange="reversed"))
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        st.subheader("No-Show Rate by Provider")
        fig2 = px.scatter(
            pw, x="total_appointments", y="no_show_rate",
            size="no_shows", color="specialty",
            hover_name="provider_name",
            labels={"total_appointments": "Total Appointments",
                    "no_show_rate": "No-Show Rate",
                    "no_shows": "# No-Shows"},
        )
        fig2.update_layout(yaxis_tickformat=".0%")
        st.plotly_chart(fig2, use_container_width=True)

    st.divider()
    col3, col4 = st.columns(2)

    with col3:
        st.subheader("No-Show Rate by Specialty")
        ns_spec = no_show_by_specialty(master)
        fig3 = px.bar(
            ns_spec, x="specialty", y="no_show_rate",
            text=ns_spec["no_show_rate"].apply(lambda x: f"{x:.0%}"),
            color="no_show_rate",
            color_continuous_scale="Reds",
            labels={"specialty": "Specialty", "no_show_rate": "No-Show Rate"},
        )
        fig3.update_traces(textposition="outside")
        fig3.update_layout(coloraxis_showscale=False, yaxis_tickformat=".0%",
                           xaxis_tickangle=-15)
        st.plotly_chart(fig3, use_container_width=True)

    with col4:
        st.subheader("Abnormal Rate by Specialty")
        ab_spec = (master[master["completed"] == 1]
                   .groupby("specialty", observed=True)
                   .agg(screenings=("appointment_id","count"),
                        abnormal=("abnormal","sum"))
                   .assign(abnormal_rate=lambda d: d["abnormal"] / d["screenings"])
                   .reset_index())
        fig4 = px.bar(
            ab_spec, x="specialty", y="abnormal_rate",
            text=ab_spec["abnormal_rate"].apply(lambda x: f"{x:.0%}"),
            color="abnormal_rate",
            color_continuous_scale="Oranges",
            labels={"specialty": "Specialty", "abnormal_rate": "Abnormal Rate"},
        )
        fig4.update_traces(textposition="outside")
        fig4.update_layout(coloraxis_showscale=False, yaxis_tickformat=".0%",
                           xaxis_tickangle=-15)
        st.plotly_chart(fig4, use_container_width=True)

    st.divider()
    st.subheader("Provider Scorecard")
    display_cols = ["provider_name", "specialty", "total_appointments",
                    "completed", "no_shows", "no_show_rate", "abnormal_rate"]
    pw_display = pw[display_cols].copy()
    pw_display["no_show_rate"]  = pw_display["no_show_rate"].apply(lambda x: f"{x:.1%}" if pd.notna(x) else "—")
    pw_display["abnormal_rate"] = pw_display["abnormal_rate"].apply(lambda x: f"{x:.1%}" if pd.notna(x) else "—")
    st.dataframe(pw_display.rename(columns={
        "provider_name": "Provider", "specialty": "Specialty",
        "total_appointments": "Total", "completed": "Completed",
        "no_shows": "No-Shows", "no_show_rate": "No-Show %",
        "abnormal_rate": "Abnormal %",
    }), use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: Geography
# ══════════════════════════════════════════════════════════════════════════════

elif PAGE_KEY == "geography":
    st.title("Geographic Analysis")
    st.markdown(f'<div class="disclaimer">{DISCLAIMER}</div>', unsafe_allow_html=True)

    state_df = appointments_by_state(master)
    fac_df   = facility_type_distribution(master)
    ttfu     = time_to_follow_up(dfs)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Appointments by State")
        fig1 = px.choropleth(
            state_df,
            locations="state",
            locationmode="USA-states",
            color="appointments",
            scope="usa",
            color_continuous_scale="Blues",
            labels={"appointments": "Appointments"},
        )
        fig1.update_layout(margin=dict(l=0, r=0, t=0, b=0))
        st.plotly_chart(fig1, use_container_width=True)

    with col2:
        st.subheader("No-Show Rate by State")
        fig2 = px.choropleth(
            state_df,
            locations="state",
            locationmode="USA-states",
            color="no_show_rate",
            scope="usa",
            color_continuous_scale="Reds",
            labels={"no_show_rate": "No-Show Rate"},
        )
        fig2.update_layout(margin=dict(l=0, r=0, t=0, b=0))
        fig2.update_coloraxes(colorbar_tickformat=".0%")
        st.plotly_chart(fig2, use_container_width=True)

    st.divider()
    col3, col4 = st.columns(2)

    with col3:
        st.subheader("Facility Type Distribution")
        fig3 = px.pie(
            fac_df, values="appointments", names="facility_type",
            color_discrete_sequence=px.colors.qualitative.Set2,
            hole=0.3,
        )
        st.plotly_chart(fig3, use_container_width=True)

    with col4:
        st.subheader("No-Show Rate by Facility Type")
        fig4 = px.bar(
            fac_df.sort_values("no_show_rate", ascending=False),
            x="facility_type", y="no_show_rate",
            text=fac_df.sort_values("no_show_rate", ascending=False)["no_show_rate"].apply(lambda x: f"{x:.0%}"),
            color="no_show_rate",
            color_continuous_scale="Reds",
            labels={"facility_type": "Facility Type", "no_show_rate": "No-Show Rate"},
        )
        fig4.update_traces(textposition="outside")
        fig4.update_layout(coloraxis_showscale=False, yaxis_tickformat=".0%",
                           xaxis_tickangle=-15)
        st.plotly_chart(fig4, use_container_width=True)

    st.divider()
    st.subheader("Time to Follow-Up After Abnormal Screening (days)")
    if not ttfu.empty:
        col5, col6 = st.columns([2, 1])
        with col5:
            fig5 = px.histogram(
                ttfu, x="days_to_follow_up", nbins=25,
                color_discrete_sequence=["#636EFA"],
                labels={"days_to_follow_up": "Days to Follow-Up"},
            )
            st.plotly_chart(fig5, use_container_width=True)
        with col6:
            st.metric("Median Days to Follow-Up", f"{ttfu['days_to_follow_up'].median():.0f}")
            st.metric("Mean Days to Follow-Up",   f"{ttfu['days_to_follow_up'].mean():.1f}")
            st.metric("Min / Max",
                      f"{ttfu['days_to_follow_up'].min():.0f} / {ttfu['days_to_follow_up'].max():.0f}")
    else:
        st.info("No follow-up data available.")

    with st.expander("State-level detail table"):
        st.dataframe(state_df.assign(
            no_show_rate=state_df["no_show_rate"].apply(lambda x: f"{x:.1%}")
        ).rename(columns={
            "state": "State", "appointments": "Appointments",
            "patients": "Unique Patients", "no_show_rate": "No-Show Rate",
        }), use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: No-Show Predictor
# ══════════════════════════════════════════════════════════════════════════════

elif PAGE_KEY == "predictor":
    st.title("No-Show Risk Predictor")
    st.markdown(f'<div class="disclaimer">{DISCLAIMER}</div>', unsafe_allow_html=True)
    st.info(
        "This tool uses a logistic regression model trained on **synthetic** data. "
        "Risk scores are illustrative only and must not be used for clinical decisions."
    )

    # Train model (cached by data hash)
    data_hash = hash(str(len(master)))
    results = get_model(data_hash)

    if results is None:
        st.error("Model could not be trained. Check that the database exists.")
        st.stop()

    # ── Model performance panel ─────────────────────────────────────────────
    with st.expander("Model Performance (expand to view)"):
        mc1, mc2, mc3, mc4 = st.columns(4)
        mc1.metric("LR CV-AUC (5-fold)", f"{results['lr_cv_auc_mean']:.3f} ± {results['lr_cv_auc_std']:.3f}")
        mc2.metric("LR Train AUC",        f"{results['lr_auc']:.3f}")
        mc3.metric("LR Avg Precision",    f"{results['lr_ap']:.3f}")
        mc4.metric("DT CV-AUC (5-fold)", f"{results['dt_cv_auc_mean']:.3f} ± {results['dt_cv_auc_std']:.3f}")

        st.subheader("Top Predictors (Logistic Regression Coefficients)")
        coef = results["coefficients"].head(15)
        fig_coef = px.bar(
            coef.sort_values("coefficient"),
            x="coefficient", y="display_name",
            orientation="h",
            color="coefficient",
            color_continuous_scale="RdBu_r",
            labels={"coefficient": "Log-Odds Coefficient", "display_name": "Feature"},
        )
        fig_coef.add_vline(x=0, line_dash="dash", line_color="gray")
        fig_coef.update_layout(coloraxis_showscale=False)
        st.plotly_chart(fig_coef, use_container_width=True)

    st.divider()
    st.subheader("Individual Risk Calculator")

    ins = dfs["insurance_type"]["coverage_type"].unique().tolist()
    eth = dfs["patient"]["ethnicity"].dropna().unique().tolist()
    edu = dfs["patient"]["education_level"].dropna().unique().tolist()
    fac = dfs["location"]["facility_type"].dropna().unique().tolist()
    spc = dfs["provider"]["specialty"].dropna().unique().tolist()

    col_f1, col_f2, col_f3 = st.columns(3)
    with col_f1:
        age          = st.slider("Patient Age", 18, 75, 38)
        lead_time    = st.slider("Lead Time (days between booking & appointment)", 1, 90, 14)
        gender       = st.selectbox("Gender", ["F", "M", "O"])
    with col_f2:
        ethnicity    = st.selectbox("Ethnicity",        sorted(eth))
        education    = st.selectbox("Education Level",  sorted(edu))
        coverage     = st.selectbox("Insurance Type",   sorted(ins))
    with col_f3:
        facility     = st.selectbox("Facility Type",    sorted(fac))
        specialty    = st.selectbox("Provider Specialty", sorted(spc))

    if st.button("Calculate No-Show Risk", type="primary", use_container_width=True):
        patient_data = {
            "age":             age,
            "lead_time_days":  lead_time,
            "gender":          gender,
            "ethnicity":       ethnicity,
            "education_level": education,
            "coverage_type":   coverage,
            "facility_type":   facility,
            "specialty":       specialty,
        }
        prob = predict_individual(results["lr_pipeline"], patient_data)
        tier, color = risk_tier(prob)

        res_c1, res_c2, res_c3 = st.columns([1, 1, 1])
        res_c1.metric("No-Show Probability", f"{prob:.1%}")
        res_c2.metric("Risk Tier", tier)
        res_c3.metric("Show-Up Probability", f"{1 - prob:.1%}")

        gauge = go.Figure(go.Indicator(
            mode="gauge+number",
            value=round(prob * 100, 1),
            number={"suffix": "%"},
            gauge={
                "axis": {"range": [0, 100]},
                "bar":  {"color": "#2c7bb6"},
                "steps": [
                    {"range": [0, 10],   "color": "#d4edda"},
                    {"range": [10, 20],  "color": "#fff3cd"},
                    {"range": [20, 100], "color": "#f8d7da"},
                ],
                "threshold": {
                    "line": {"color": "black", "width": 3},
                    "thickness": 0.75,
                    "value": prob * 100,
                },
            },
            title={"text": "No-Show Risk Score"},
        ))
        gauge.update_layout(height=280)
        st.plotly_chart(gauge, use_container_width=True)

        st.caption(
            "Interpretation: Green (<10%) = low risk, Amber (10–20%) = moderate, "
            "Red (>20%) = elevated. These thresholds are illustrative; real deployment "
            "requires validation on real clinical data."
        )

    st.divider()
    st.subheader("Population-Level No-Show Distribution")
    prob_col = master.copy()
    prob_col["predicted_prob"] = results["y_prob_lr"]
    fig_hist = px.histogram(
        prob_col, x="predicted_prob", color="status",
        nbins=30, barmode="overlay", opacity=0.7,
        labels={"predicted_prob": "Predicted No-Show Probability", "status": "Actual Status"},
        color_discrete_map={
            "No-Show":   "#EF553B",
            "Completed": "#00CC96",
            "Cancelled": "#AB63FA",
            "Scheduled": "#636EFA",
        },
    )
    fig_hist.update_layout(xaxis_tickformat=".0%")
    st.plotly_chart(fig_hist, use_container_width=True)
